management:
  endpoints:
    #disable all default endpoints
    enabled-by-default: false
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
      enabled: true
    info:
      enabled: true